version: "3.8"

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: "quisco-nextjs"
      POSTGRES_DB: "quisco-nextjs"
      POSTGRES_PASSWORD: "quisco-nextjs"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
